### ISSUE TITLE
License declaration mismatch

### ISSUE THREAD

**Issue by sschuberth** [EsotericSoftware/minlog#5]
In the repo, the [license.txt](https://github.com/EsotericSoftware/minlog/blob/master/license.txt) is a 3-clause BSD license. The pom.xml [refers to this](https://github.com/EsotericSoftware/minlog/blob/master/pom.xml#L21) as "New BSD License" (which is ok, as that is an alternative name for "The BSD 3-Clause License"), but [the link](https://github.com/EsotericSoftware/minlog/blob/master/pom.xml#L22) points to [The BSD 2-Clause License](http://www.opensource.org/licenses/bsd-license.php).

I'd propose to fix this by making the pom.xml read:

```
    <license>
        <name>The BSD 3-Clause License</name>
        <url>http://opensource.org/licenses/BSD-3-Clause</url>
        <distribution>repo</distribution>
    </license>
```

**Comment by sschuberth** [comment]
BTW, the [kryo](https://github.com/EsotericSoftware/kryo) and [reflectasm](https://github.com/EsotericSoftware/reflectasm) projects do seem to have exactly the same issue.

**Comment by SoltauFintel** [comment]
I would prefer MIT license!

**Comment by sschuberth** [comment]
@SoltauFintel Please note that I did not intend to discuss the choice of license itself here, but only to document consistently whatever the choice is.

**Comment by NathanSweet** [comment]
The POM should match the license (3-clause BSD). Would you like to submit a PR to the affected projects?

**Comment by sschuberth** [comment]
Sure, I'll do that. I just didn't want to until I knew what the license *should* be. I'll push something soon.

**Comment by NathanSweet** [comment]
Great, thank you!
