### ISSUE TITLE
android build exception

### ISSUE THREAD

**Issue by fabiitch** [EsotericSoftware/minlog#8]
My android gradle

i got this error first : 

> GPBI: {"kind":"error","text":"Error converting bytecode to dex:\nCause: com.android.dex.DexException: Multiple dex files define Lcom/esotericsoftware/minlog/Log$Logger;","sources":[{}],"original":"UNEXPECTED TOP-LEVEL EXCEPTION:\ncom.android.dex.DexException: Multiple dex files define Lcom/esotericsoftware/minlog/Log$Logger;\n\tat com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)\n\tat com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)\n\tat com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)\n\tat com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)\n\tat com.android.dx.merge.DexMerger.merge(DexMerger.java:189)\n\tat com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)\n\tat com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)\n\tat com.android.dx.command.dexer.Main.run(Main.java:277)\n\tat com.android.dx.command.dexer.Main.main(Main.java:245)\n\tat com.android.dx.command.Main.main(Main.java:106)\n","tool":"Dex"}

> 

i change this of my android build.gradle
defaultConfig {
        applicationId "com.nzt.mwa"
        minSdkVersion 9
        targetSdkVersion 20
        versionCode 1
        versionName "1.0"
         multiDexEnabled true //here !!
    }

Now new error 🥇 
* What went wrong:
Execution failed for task ':android:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/esotericsoftware/minlog/Log$Logger.class

Any idea ?

**Comment by NathanSweet** [comment]
> Multiple dex files define Lcom/esotericsoftware/minlog/Log$Logger
Sounds like you include minlog twice.
